(ns com.google.cloud.dataproc.v1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.dataproc.v1.ClusterControllerClient$ListClustersFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1.ClusterControllerClient$ListClustersPage])
(require '[com.google.cloud.dataproc.v1.ClusterControllerClient$ListClustersPagedResponse])
(require '[com.google.cloud.dataproc.v1.ClusterControllerClient])
(require '[com.google.cloud.dataproc.v1.ClusterControllerSettings$Builder])
(require '[com.google.cloud.dataproc.v1.ClusterControllerSettings])
(require '[com.google.cloud.dataproc.v1.JobControllerClient$ListJobsFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1.JobControllerClient$ListJobsPage])
(require '[com.google.cloud.dataproc.v1.JobControllerClient$ListJobsPagedResponse])
(require '[com.google.cloud.dataproc.v1.JobControllerClient])
(require '[com.google.cloud.dataproc.v1.JobControllerSettings$Builder])
(require '[com.google.cloud.dataproc.v1.JobControllerSettings])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceClient$ListWorkflowTemplatesFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceClient$ListWorkflowTemplatesPage])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceClient$ListWorkflowTemplatesPagedResponse])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceClient])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceSettings$Builder])
(require '[com.google.cloud.dataproc.v1.WorkflowTemplateServiceSettings])
