(ns com.google.cloud.websecurityscanner.v1alpha.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListCrawledUrlsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListCrawledUrlsPage])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListCrawledUrlsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListFindingsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListFindingsPage])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListFindingsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanConfigsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanConfigsPage])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanConfigsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanRunsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanRunsPage])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient$ListScanRunsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerClient])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerSettings$Builder])
(require '[com.google.cloud.websecurityscanner.v1alpha.WebSecurityScannerSettings])
