(ns com.google.cloud.errorreporting.v1beta1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.errorreporting.v1beta1.ErrorGroupServiceClient])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorGroupServiceSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorGroupServiceSettings])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListEventsFixedSizeCollection])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListEventsPage])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListEventsPagedResponse])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListGroupStatsFixedSizeCollection])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListGroupStatsPage])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient$ListGroupStatsPagedResponse])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceClient])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.ErrorStatsServiceSettings])
(require '[com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceClient])
(require '[com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.ReportErrorsServiceSettings])
