(ns com.google.cloud.vision.v1p3beta1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.vision.v1p3beta1.ImageAnnotatorClient])
(require '[com.google.cloud.vision.v1p3beta1.ImageAnnotatorSettings$Builder])
(require '[com.google.cloud.vision.v1p3beta1.ImageAnnotatorSettings])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductSetsFixedSizeCollection])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductSetsPage])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductSetsPagedResponse])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsFixedSizeCollection])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsInProductSetFixedSizeCollection])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsInProductSetPage])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsInProductSetPagedResponse])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsPage])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListProductsPagedResponse])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListReferenceImagesFixedSizeCollection])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListReferenceImagesPage])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient$ListReferenceImagesPagedResponse])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchClient])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchSettings$Builder])
(require '[com.google.cloud.vision.v1p3beta1.ProductSearchSettings])
