(ns com.google.cloud.dataproc.v1.stub.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.dataproc.v1.stub.ClusterControllerStub])
(require '[com.google.cloud.dataproc.v1.stub.ClusterControllerStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1.stub.ClusterControllerStubSettings])
(require '[com.google.cloud.dataproc.v1.stub.GrpcClusterControllerCallableFactory])
(require '[com.google.cloud.dataproc.v1.stub.GrpcClusterControllerStub])
(require '[com.google.cloud.dataproc.v1.stub.GrpcJobControllerCallableFactory])
(require '[com.google.cloud.dataproc.v1.stub.GrpcJobControllerStub])
(require '[com.google.cloud.dataproc.v1.stub.GrpcWorkflowTemplateServiceCallableFactory])
(require '[com.google.cloud.dataproc.v1.stub.GrpcWorkflowTemplateServiceStub])
(require '[com.google.cloud.dataproc.v1.stub.JobControllerStub])
(require '[com.google.cloud.dataproc.v1.stub.JobControllerStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1.stub.JobControllerStubSettings])
(require '[com.google.cloud.dataproc.v1.stub.WorkflowTemplateServiceStub])
(require '[com.google.cloud.dataproc.v1.stub.WorkflowTemplateServiceStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1.stub.WorkflowTemplateServiceStubSettings])
