(ns com.google.cloud.firestore.v1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListFieldsFixedSizeCollection])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListFieldsPage])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListFieldsPagedResponse])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListIndexesFixedSizeCollection])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListIndexesPage])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient$ListIndexesPagedResponse])
(require '[com.google.cloud.firestore.v1.FirestoreAdminClient])
(require '[com.google.cloud.firestore.v1.FirestoreAdminSettings$Builder])
(require '[com.google.cloud.firestore.v1.FirestoreAdminSettings])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListCollectionIdsFixedSizeCollection])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListCollectionIdsPage])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListCollectionIdsPagedResponse])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListDocumentsFixedSizeCollection])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListDocumentsPage])
(require '[com.google.cloud.firestore.v1.FirestoreClient$ListDocumentsPagedResponse])
(require '[com.google.cloud.firestore.v1.FirestoreClient])
(require '[com.google.cloud.firestore.v1.FirestoreSettings$Builder])
(require '[com.google.cloud.firestore.v1.FirestoreSettings])
