(ns com.google.cloud.resourcemanager.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.resourcemanager.Project$Builder])
(require '[com.google.cloud.resourcemanager.Project])
(require '[com.google.cloud.resourcemanager.ProjectInfo$Builder])
(require '[com.google.cloud.resourcemanager.ProjectInfo$ResourceId])
(require '[com.google.cloud.resourcemanager.ProjectInfo$State])
(require '[com.google.cloud.resourcemanager.ProjectInfo])
(require '[com.google.cloud.resourcemanager.ResourceManager$ProjectField])
(require '[com.google.cloud.resourcemanager.ResourceManager$ProjectGetOption])
(require '[com.google.cloud.resourcemanager.ResourceManager$ProjectListOption])
(require '[com.google.cloud.resourcemanager.ResourceManager])
(require '[com.google.cloud.resourcemanager.ResourceManagerException])
(require '[com.google.cloud.resourcemanager.ResourceManagerFactory])
(require '[com.google.cloud.resourcemanager.ResourceManagerOptions$Builder])
(require '[com.google.cloud.resourcemanager.ResourceManagerOptions$DefaultResourceManagerFactory])
(require '[com.google.cloud.resourcemanager.ResourceManagerOptions$DefaultResourceManagerRpcFactory])
(require '[com.google.cloud.resourcemanager.ResourceManagerOptions])
