(ns com.google.cloud.errorreporting.v1beta1.stub.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorGroupServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorGroupServiceStubSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorGroupServiceStubSettings])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorStatsServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorStatsServiceStubSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ErrorStatsServiceStubSettings])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcErrorGroupServiceCallableFactory])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcErrorGroupServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcErrorStatsServiceCallableFactory])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcErrorStatsServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcReportErrorsServiceCallableFactory])
(require '[com.google.cloud.errorreporting.v1beta1.stub.GrpcReportErrorsServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ReportErrorsServiceStub])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ReportErrorsServiceStubSettings$Builder])
(require '[com.google.cloud.errorreporting.v1beta1.stub.ReportErrorsServiceStubSettings])
