(ns com.google.cloud.kms.v1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeyVersionsFixedSizeCollection])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeyVersionsPage])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeyVersionsPagedResponse])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeysFixedSizeCollection])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeysPage])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListCryptoKeysPagedResponse])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListImportJobsFixedSizeCollection])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListImportJobsPage])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListImportJobsPagedResponse])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListKeyRingsFixedSizeCollection])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListKeyRingsPage])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient$ListKeyRingsPagedResponse])
(require '[com.google.cloud.kms.v1.KeyManagementServiceClient])
(require '[com.google.cloud.kms.v1.KeyManagementServiceSettings$Builder])
(require '[com.google.cloud.kms.v1.KeyManagementServiceSettings])
