(ns com.google.cloud.websecurityscanner.v1beta.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListCrawledUrlsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListCrawledUrlsPage])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListCrawledUrlsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListFindingsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListFindingsPage])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListFindingsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanConfigsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanConfigsPage])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanConfigsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanRunsFixedSizeCollection])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanRunsPage])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient$ListScanRunsPagedResponse])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerClient])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerSettings$Builder])
(require '[com.google.cloud.websecurityscanner.v1beta.WebSecurityScannerSettings])
