(ns com.google.cloud.bigquery.datatransfer.v1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListDataSourcesFixedSizeCollection])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListDataSourcesPage])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListDataSourcesPagedResponse])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferConfigsFixedSizeCollection])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferConfigsPage])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferConfigsPagedResponse])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferLogsFixedSizeCollection])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferLogsPage])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferLogsPagedResponse])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferRunsFixedSizeCollection])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferRunsPage])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient$ListTransferRunsPagedResponse])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceClient])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceSettings$Builder])
(require '[com.google.cloud.bigquery.datatransfer.v1.DataTransferServiceSettings])
(require '[com.google.cloud.bigquery.datatransfer.v1.SampleApp])
