(ns com.google.cloud.dataproc.v1beta2.stub.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.dataproc.v1beta2.stub.AutoscalingPolicyServiceStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.AutoscalingPolicyServiceStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.stub.AutoscalingPolicyServiceStubSettings])
(require '[com.google.cloud.dataproc.v1beta2.stub.ClusterControllerStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.ClusterControllerStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.stub.ClusterControllerStubSettings])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcAutoscalingPolicyServiceCallableFactory])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcAutoscalingPolicyServiceStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcClusterControllerCallableFactory])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcClusterControllerStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcJobControllerCallableFactory])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcJobControllerStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcWorkflowTemplateServiceCallableFactory])
(require '[com.google.cloud.dataproc.v1beta2.stub.GrpcWorkflowTemplateServiceStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.JobControllerStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.JobControllerStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.stub.JobControllerStubSettings])
(require '[com.google.cloud.dataproc.v1beta2.stub.WorkflowTemplateServiceStub])
(require '[com.google.cloud.dataproc.v1beta2.stub.WorkflowTemplateServiceStubSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.stub.WorkflowTemplateServiceStubSettings])
