(ns core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.videointelligence.v1.core])
(require '[com.google.cloud.videointelligence.v1.stub.core])
(require '[com.google.cloud.videointelligence.v1beta1.core])
(require '[com.google.cloud.videointelligence.v1beta1.stub.core])
(require '[com.google.cloud.videointelligence.v1beta2.core])
(require '[com.google.cloud.videointelligence.v1beta2.stub.core])
(require '[com.google.cloud.videointelligence.v1p1beta1.core])
(require '[com.google.cloud.videointelligence.v1p1beta1.stub.core])
(require '[com.google.cloud.videointelligence.v1p2beta1.core])
(require '[com.google.cloud.videointelligence.v1p2beta1.stub.core])
(require '[com.google.cloud.videointelligence.v1p3beta1.core])
(require '[com.google.cloud.videointelligence.v1p3beta1.stub.core])
