(ns com.google.cloud.automl.v1beta1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListColumnSpecsFixedSizeCollection])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListColumnSpecsPage])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListColumnSpecsPagedResponse])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListDatasetsFixedSizeCollection])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListDatasetsPage])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListDatasetsPagedResponse])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelEvaluationsFixedSizeCollection])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelEvaluationsPage])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelEvaluationsPagedResponse])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelsFixedSizeCollection])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelsPage])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListModelsPagedResponse])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListTableSpecsFixedSizeCollection])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListTableSpecsPage])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient$ListTableSpecsPagedResponse])
(require '[com.google.cloud.automl.v1beta1.AutoMlClient])
(require '[com.google.cloud.automl.v1beta1.AutoMlSettings$Builder])
(require '[com.google.cloud.automl.v1beta1.AutoMlSettings])
(require '[com.google.cloud.automl.v1beta1.PredictionServiceClient])
(require '[com.google.cloud.automl.v1beta1.PredictionServiceSettings$Builder])
(require '[com.google.cloud.automl.v1beta1.PredictionServiceSettings])
