(ns com.google.cloud.logging.v2.stub.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.logging.v2.stub.ConfigServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.ConfigServiceV2StubSettings$Builder])
(require '[com.google.cloud.logging.v2.stub.ConfigServiceV2StubSettings])
(require '[com.google.cloud.logging.v2.stub.GrpcConfigServiceV2CallableFactory])
(require '[com.google.cloud.logging.v2.stub.GrpcConfigServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.GrpcLoggingServiceV2CallableFactory])
(require '[com.google.cloud.logging.v2.stub.GrpcLoggingServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.GrpcMetricsServiceV2CallableFactory])
(require '[com.google.cloud.logging.v2.stub.GrpcMetricsServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.LoggingServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.LoggingServiceV2StubSettings$Builder])
(require '[com.google.cloud.logging.v2.stub.LoggingServiceV2StubSettings])
(require '[com.google.cloud.logging.v2.stub.MetricsServiceV2Stub])
(require '[com.google.cloud.logging.v2.stub.MetricsServiceV2StubSettings$Builder])
(require '[com.google.cloud.logging.v2.stub.MetricsServiceV2StubSettings])
