(ns com.google.cloud.dataproc.v1beta2.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceClient$ListAutoscalingPoliciesFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceClient$ListAutoscalingPoliciesPage])
(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceClient$ListAutoscalingPoliciesPagedResponse])
(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceClient])
(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.AutoscalingPolicyServiceSettings])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerClient$ListClustersFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerClient$ListClustersPage])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerClient$ListClustersPagedResponse])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerClient])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.ClusterControllerSettings])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerClient$ListJobsFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerClient$ListJobsPage])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerClient$ListJobsPagedResponse])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerClient])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.JobControllerSettings])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceClient$ListWorkflowTemplatesFixedSizeCollection])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceClient$ListWorkflowTemplatesPage])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceClient$ListWorkflowTemplatesPagedResponse])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceClient])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceSettings$Builder])
(require '[com.google.cloud.dataproc.v1beta2.WorkflowTemplateServiceSettings])
