(ns com.google.cloud.securitycenter.v1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupAssetsFixedSizeCollection])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupAssetsPage])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupAssetsPagedResponse])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupFindingsFixedSizeCollection])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupFindingsPage])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$GroupFindingsPagedResponse])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListAssetsFixedSizeCollection])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListAssetsPage])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListAssetsPagedResponse])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListFindingsFixedSizeCollection])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListFindingsPage])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListFindingsPagedResponse])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListSourcesFixedSizeCollection])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListSourcesPage])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient$ListSourcesPagedResponse])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterClient])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterSettings$Builder])
(require '[com.google.cloud.securitycenter.v1.SecurityCenterSettings])
