(ns com.google.cloud.dlp.v2.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDeidentifyTemplatesFixedSizeCollection])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDeidentifyTemplatesPage])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDeidentifyTemplatesPagedResponse])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDlpJobsFixedSizeCollection])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDlpJobsPage])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListDlpJobsPagedResponse])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListInspectTemplatesFixedSizeCollection])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListInspectTemplatesPage])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListInspectTemplatesPagedResponse])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListJobTriggersFixedSizeCollection])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListJobTriggersPage])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListJobTriggersPagedResponse])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListStoredInfoTypesFixedSizeCollection])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListStoredInfoTypesPage])
(require '[com.google.cloud.dlp.v2.DlpServiceClient$ListStoredInfoTypesPagedResponse])
(require '[com.google.cloud.dlp.v2.DlpServiceClient])
(require '[com.google.cloud.dlp.v2.DlpServiceSettings$Builder])
(require '[com.google.cloud.dlp.v2.DlpServiceSettings])
