(ns com.google.cloud.datastore.Transaction$Response
  (:refer-clojure :only [require comment defn ->])
  (:import [com.google.cloud.datastore Transaction$Response]))

(defn get-generated-keys
  "Returns a list of keys generated by a transaction.

  returns: `java.util.List<com.google.cloud.datastore.Key>`"
  (^java.util.List [^Transaction$Response this]
    (-> this (.getGeneratedKeys))))

