(ns com.google.cloud.devtools.containeranalysis.v1beta1.core
  (:refer-clojure :only [require comment defn ->])
  (:import ))

(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Client$ListScanConfigsFixedSizeCollection])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Client$ListScanConfigsPage])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Client$ListScanConfigsPagedResponse])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Client])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Settings$Builder])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Settings])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNoteOccurrencesFixedSizeCollection])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNoteOccurrencesPage])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNoteOccurrencesPagedResponse])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNotesFixedSizeCollection])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNotesPage])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListNotesPagedResponse])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListOccurrencesFixedSizeCollection])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListOccurrencesPage])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client$ListOccurrencesPagedResponse])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Client])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Settings$Builder])
(require '[com.google.cloud.devtools.containeranalysis.v1beta1.GrafeasV1Beta1Settings])
